name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy ML_DL to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_REPO: ${{ secrets.HF_REPO }}
      run: |
        cd Deploiement_ML_DL
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote add origin "https://__token__:${HF_TOKEN}@huggingface.co/${HF_REPO}.git"
        git checkout -b main
        git add .
        git commit -m "Deploy app to Hugging Face"
        git push --force origin main
