name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Install DVC
      run: |
        pip install dvc
        
    - name: Validate DVC pipeline
      run: |
        dvc version
        
        if [ -f dvc.yaml ]; then
          sed -i 's|\.venv/bin/python|python|g' dvc.yaml
        fi
        
        # Exécution du pipeline DVC
        dvc repro --force preprocess train evaluate report
        dvc status